### ISSUE TITLE
Name change?

### ISSUE THREAD

**Issue by ricea** [ricea/compressstream-explainer#6]
We have been discussing whether "CompressStream" is the best name for the interface. Options we are currently considering:

1. CompressStream
2. CompressionStream
3. Compressor
4. Others?

Please let us know what you think.

**Comment by yoavweiss** [comment]
I think "Compression Streams" would be a good name for the feature where `CompressStream` and `DecompressStream` would be good API names for the actual objects responsible for each.

**Comment by ricea** [comment]
@yoavweiss Thanks. I am a bit worried that the 3 consecutive S's in `CompressStream` could make it hard to type. Actually, I typed `CompresssStream` just now :smile:.

**Comment by yoavweiss** [comment]
Good point. So maybe `CompressionStream` and `DecompressionStream`?

**Comment by guest271314** [comment]
FWIW `CompressionStream`, `DecompressionStream`.  

Can "Decompress a Blob to a Blob" be explained further? Does that mean input `blob` MIME type is `application/x-gzip`? What is output `Blob` MIME type in that code example?

**Comment by ricea** [comment]
@guest271314 The function ignores the input mime type. The mime type of the created blob is empty. I will try to add some extra explanation.
